routes:
  /notes/:
    template: post-extended
    controller: channel
    filter: 'tag:notes'
    data: tag.notes
  /diary/:
    template: post-extended
    controller: channel
    filter: tag:notes
    data: tag.now
  /archive/:
    template: archive
    controller: channel
    data: tag.archive

collections:
  /essays/:
    permalink: /{slug}/
    template: essays
    filter: tag:atomic-essay
    data: tag.atomic-essay
  /works/:
    permalink: /{slug}/
    template: portfolios
    filter: primary_tag:portfolios
    data: tag.portfolios
  /side-projects/:
    permalink: /{slug}/
    template: essays
    filter: primary_tag:side-projects
    data: tag.side-projects
  /:
    data: page.home
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
